### ISSUE TITLE
ICS3U Blackjack Assignment

### ISSUE THREAD

**Issue by JustIn-BorrowMayo** [JustIn-BorrowMayo/ICS3U#2]
https://github.com/JustIn-BorrowMayo/ICS3U/blob/master/ICS3U%20Blackjack%20Assignment/src/com/bayviewglen/blackjack/BlackjackAssignment.java

**Comment by kevindeslauriers** [comment]
Excellent Work Justin.  Your code was very well organised and commented. 

100%
