### ISSUE TITLE
ICS3U Horse Racing

### ISSUE THREAD

**Issue by JustIn-BorrowMayo** [JustIn-BorrowMayo/ICS3U#3]
https://github.com/JustIn-BorrowMayo/ICS3U/blob/master/ICS3U%20Unit%20Six/src/com/bayviewglen/horseracing/HorseRacing.java

playerData.dat and horses.dat are in my input folder

**Comment by kevindeslauriers** [comment]
Excellent Work - Your methods were well written and your code is very organised.

Here is the feedback that I have for you:
Requirements:
You should not ask the user how many horses are in the race - this should be random and chosen for them.
Each iteration of a race should allow you to choose which user is betting and you should have the ability to allow for a user to bet on a horse and another user to also bet on a horse.
Displaying 0 as a # and not 1 is not very user friendly.

96%
